/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>

#include "bakery.h"


void
bakeryprogram_1(char *host)
{
	CLIENT *clnt;
	struct BakeryOrder  *result_1;
	struct BakeryOrder  getorder_1_arg;
	struct BakeryOrder  *result_2;
	struct BakeryOrder  waitinqueue_1_arg;
	struct BakeryOrder  *result_3;
	struct BakeryOrder  processbakeryresult_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BakeryProgram, BakeryVerision, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	sleep(5);
	getorder_1_arg.pid = getpid();
	result_1 = getorder_1(&getorder_1_arg, clnt);
	if (result_1 == (struct BakeryOrder *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Client %d has number %d\n", getorder_1_arg.pid, result_1->order_num);
	sleep(5);
	waitinqueue_1_arg.order_num = result_1->order_num;
	waitinqueue_1_arg.pid = result_1->pid;
	result_2 = waitinqueue_1(&waitinqueue_1_arg, clnt);
	if (result_2 == (struct BakeryOrder *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	sleep(5);
	processbakeryresult_1_arg.order_num = waitinqueue_1_arg.order_num;
	processbakeryresult_1_arg.pid = waitinqueue_1_arg.pid;
	result_3 = processbakeryresult_1(&processbakeryresult_1_arg, clnt);
	if (result_3 == (struct BakeryOrder *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Client %d got response %c (sleep = 5)\n", getorder_1_arg.pid, result_3->order_result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakeryprogram_1 (host);
exit (0);
}
