/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct BakeryOrder {
	int order_num;
	int pid;
	int order_result;
};
typedef struct BakeryOrder BakeryOrder;

#define BakeryProgram 0x20000001
#define BakeryVerision 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetOrder 1
extern  struct BakeryOrder * getorder_1(struct BakeryOrder *, CLIENT *);
extern  struct BakeryOrder * getorder_1_svc(struct BakeryOrder *, struct svc_req *);
#define WaitInQueue 2
extern  struct BakeryOrder * waitinqueue_1(struct BakeryOrder *, CLIENT *);
extern  struct BakeryOrder * waitinqueue_1_svc(struct BakeryOrder *, struct svc_req *);
#define ProcessBakeryResult 3
extern  struct BakeryOrder * processbakeryresult_1(struct BakeryOrder *, CLIENT *);
extern  struct BakeryOrder * processbakeryresult_1_svc(struct BakeryOrder *, struct svc_req *);
extern int bakeryprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetOrder 1
extern  struct BakeryOrder * getorder_1();
extern  struct BakeryOrder * getorder_1_svc();
#define WaitInQueue 2
extern  struct BakeryOrder * waitinqueue_1();
extern  struct BakeryOrder * waitinqueue_1_svc();
#define ProcessBakeryResult 3
extern  struct BakeryOrder * processbakeryresult_1();
extern  struct BakeryOrder * processbakeryresult_1_svc();
extern int bakeryprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BakeryOrder (XDR *, BakeryOrder*);

#else /* K&R C */
extern bool_t xdr_BakeryOrder ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
